In [1]:
import pandas as pd

In [4]:
df=pd.read_excel('large_ml_cleaning_practice.xlsx')
df.head()

,Player_ID,Player_Name,Team,Matches_Played,Runs_Scored,Batting_Avg,Strike_Rate,Wickets,Economy_Rate,Role,Salary_Lakhs,Fitness_Status
0,1001,Jos Sharma,West Indies,71,566,26.34,96.84,99.0,11.35,batsman,72.0,Injured
1,1002,Nicholas Rabada,ENGLAND,45,NaN,NaN,144.26,18.0,10.00,BOWLER,1172.0,Rehab
2,1003,Quinton Warner,INDIA,132,935,25.88,NaN,93.0,9.26,BOWLER,1238.0,Injured
3,1004,Glenn Dhoni,Sri Lanka,36,1934,28.10,130.04,112.0,7.17,BOWLER,NaN,NaN
4,1005,Dasun Yadav,West Indies,70,2708,54.52,134.24,145.0,10.77,Bowler,144.0,Fit

In [16]:
df.isnull().sum()

Player_ID          0
Player_Name        0
Team               0
Matches_Played     1
Runs_Scored       50
Batting_Avg       44
Strike_Rate       45
Wickets           49
Economy_Rate      37
Role               0
Salary_Lakhs      53
Fitness_Status    47
dtype: int64

In [27]:

from sklearn.preprocessing import LabelEncoder
la=LabelEncoder()
df['Encoded'] = la.fit_transform(df['Role'])
df

,Player_ID,Player_Name,Team,Matches_Played,Runs_Scored,Batting_Avg,Strike_Rate,Wickets,Economy_Rate,Role,Salary_Lakhs,Fitness_Status,Team_Encoded,Encoded
0,1001,Jos Sharma,15,71,566,26.34,96.84,99.0,11.35,batsman,72.0,Injured,15,8
1,1002,Nicholas Rabada,6,45,NaN,NaN,144.26,18.0,10.00,BOWLER,1172.0,Rehab,6,1
2,1003,Quinton Warner,8,132,935,25.88,NaN,93.0,9.26,BOWLER,1238.0,Injured,8,1
3,1004,Glenn Dhoni,14,36,1934,28.10,130.04,112.0,7.17,BOWLER,NaN,NaN,14,1
4,1005,Dasun Yadav,15,70,2708,54.52,134.24,145.0,10.77,Bowler,144.0,Fit,15,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,1446,Kagiso Stokes,14,90,920,34.82,94.90,0.0,11.71,Wicket-Keeper,2021.0,Rehab,14,6
446,1447,Quinton Dhoni,1,110,NaN,32.28,149.54,107.0,8.71,Bowler,2153.0,NaN,1,3
447,1448,Dasun Maxwell,0,57,2769,27.22,154.59,18.0,6.69,batsman,2249.0,Rehab,0,8
448,1449,Glenn Hasaranga,9,1,3232,5.73,178.20,75.0,8.50,Bowler,495.0,Rehab,9,3
449,1450,Mitchell Klaasen,10,63,15,34.35,100.98,71.0,9.76,Bowler,NaN,Rehab,10,3

Ordinal Encoding from sklearn

In [6]:
import pandas as pd
df1=pd.DataFrame({"size":["s","m","l","xl","m","l","xl","s","m","l","xl","s","m","xl","s","l","xl" ]})
ord_data=[["s",'m','l','xl']]
from sklearn.preprocessing import OrdinalEncoder
ord_enc=OrdinalEncoder(categories=ord_data)
df1['Encoded'] = ord_enc.fit_transform(df1[['size']])
df1

   size  Encoded
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     m      1.0
5     l      2.0
6    xl      3.0
7     s      0.0
8     m      1.0
9     l      2.0
10   xl      3.0
11    s      0.0
12    m      1.0
13   xl      3.0
14    s      0.0
15    l      2.0
16   xl      3.0

Ordinal Encoding by Map Function

In [7]:
ord_data1={"s":1,"m":2,"l":3,"xl":4}
df1['Encoded1']=df1['size'].map(ord_data1)
df1

   size  Encoded  Encoded1
0     s      0.0         1
1     m      1.0         2
2     l      2.0         3
3    xl      3.0         4
4     m      1.0         2
5     l      2.0         3
6    xl      3.0         4
7     s      0.0         1
8     m      1.0         2
9     l      2.0         3
10   xl      3.0         4
11    s      0.0         1
12    m      1.0         2
13   xl      3.0         4
14    s      0.0         1
15    l      2.0         3
16   xl      3.0         4